//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1590.0.
// 
namespace TouchRemote.Model.Persistence {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schneenet.com/Buttons.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schneenet.com/Buttons.xsd", IsNullable=false)]
    public partial class Buttons {
        
        private Element[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Button", typeof(Button))]
        [System.Xml.Serialization.XmlElementAttribute("ToggleButton", typeof(ToggleButton))]
        public Element[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schneenet.com/Buttons.xsd")]
    public partial class Button : Element {
        
        private ActionExecutable buttonClickActionField;
        
        private string labelField;
        
        private string iconField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Button.ClickAction")]
        public ActionExecutable ButtonClickAction {
            get {
                return this.buttonClickActionField;
            }
            set {
                this.buttonClickActionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schneenet.com/Buttons.xsd")]
    public partial class ActionExecutable {
        
        private System.Xml.XmlElement anyField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ToggleButton))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Button))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schneenet.com/Buttons.xsd")]
    public partial class Element {
        
        private string idField;
        
        private double xField;
        
        private double yField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schneenet.com/Buttons.xsd")]
    public partial class ToggleButton : Element {
        
        private ActionExecutable toggleButtonToggleOnActionField;
        
        private ActionExecutable toggleButtonToggleOffActionField;
        
        private string labelOnField;
        
        private string iconOnField;
        
        private string labelOffField;
        
        private string iconOffField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ToggleButton.ToggleOnAction")]
        public ActionExecutable ToggleButtonToggleOnAction {
            get {
                return this.toggleButtonToggleOnActionField;
            }
            set {
                this.toggleButtonToggleOnActionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ToggleButton.ToggleOffAction")]
        public ActionExecutable ToggleButtonToggleOffAction {
            get {
                return this.toggleButtonToggleOffActionField;
            }
            set {
                this.toggleButtonToggleOffActionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LabelOn {
            get {
                return this.labelOnField;
            }
            set {
                this.labelOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IconOn {
            get {
                return this.iconOnField;
            }
            set {
                this.iconOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LabelOff {
            get {
                return this.labelOffField;
            }
            set {
                this.labelOffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IconOff {
            get {
                return this.iconOffField;
            }
            set {
                this.iconOffField = value;
            }
        }
    }
}
